--- #YAML:1.0
name:                Shell
version:             0.71
abstract:            run shell commands transparently within perl
license:             perl
generated_by:        ExtUtils::MakeMaker version 6.30_01
author:              ~
distribution_type:   module
requires:     
    Test::More:                    0
meta-spec:
    url: <http://module-build.sourceforge.net/META-spec-new.html>;
    version: 1.1
